# Generated by Django 3.2 on 2022-11-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0009_aimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='is_selected',
            field=models.CharField(choices=[('CNN 모델 - 1', 'CNN모델 - 1'), ('CNN 모델 - 2', 'CNN모델 - 2'), ('CNN 모델 - 3', 'CNN모델 - 3'), ('CNN 모델 - 4', 'CNN모델 - 4'), ('CNN 모델 - 5', 'CNN모델 - 5')], max_length=20, verbose_name='AI 모델'),
        ),
    ]
