# Generated by Django 3.2 on 2022-11-23 05:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0010_alter_aimodel_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='id',
        ),
        migrations.AddField(
            model_name='result',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signlanguage.aimodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='ai_file',
            field=models.FileField(blank=True, unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='is_selected',
            field=models.CharField(choices=[('CNN 모델 - 1', 'CNN모델 - 1'), ('CNN 모델 - 2', 'CNN모델 - 2'), ('CNN 모델 - 3', 'CNN모델 - 3'), ('CNN 모델 - 4', 'CNN모델 - 4'), ('CNN 모델 - 5', 'CNN모델 - 5')], max_length=20, primary_key=True, serialize=False, verbose_name='AI 모델'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 14, 3, 28, 724249), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='result',
            name='correct',
            field=models.CharField(default='wrong', max_length=10),
        ),
    ]
