# Generated by Django 3.2 on 2022-11-23 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0011_auto_20221123_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 14, 11, 10, 162164), verbose_name='date published'),
        ),
    ]
