# Generated by Django 3.2 on 2022-11-23 06:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0021_alter_aimodel_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 15, 31, 15, 995735), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='result',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signlanguage.aimodel'),
        ),
    ]
