# Generated by Django 3.2 on 2022-11-23 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0022_auto_20221123_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 16, 4, 6, 729404), verbose_name='date published'),
        ),
    ]
