# Generated by Django 3.2 on 2022-11-23 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0024_auto_20221123_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='accuracy',
            field=models.FloatField(default=0.0, verbose_name='Accuracy'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 22, 55, 16, 861625), verbose_name='date published'),
        ),
    ]
