# Generated by Django 3.2 on 2022-11-23 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0025_auto_20221123_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='is_selected',
            field=models.CharField(choices=[('CNN model - 1', 'CNN model - 1'), ('CNN model - 2', 'CNN model - 2'), ('CNN model - 3', 'CNN model - 3'), ('CNN model - 4', 'CNN model - 4'), ('CNN model - 5', 'CNN model - 5')], max_length=20, primary_key=True, serialize=False, verbose_name='AI 모델'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 0, 7, 33, 830241), verbose_name='date published'),
        ),
    ]
